import type { ThemeDefinition } from './types.js'

/**
 * 內建主題。
 *
 * 每一套都已通過 analyzeTheme 的 AA 檢查 —— 有測試守著。
 * 使用者第一次進來看到的東西不該有無障礙問題。
 */

const baseTypography = {
  headingFontId: 'noto-serif-tc',
  bodyFontId: 'noto-sans-tc',
  uiFontId: 'inter',
  monoFontId: 'jetbrains-mono',
  headingScale: 1,
  bodyScale: 1,
  lineHeight: 1.7,
  letterSpacing: 0,
}

export const PRESET_THEMES: ThemeDefinition[] = [
  {
    schemaVersion: 1,
    name: '粉霧',
    colors: {
      primary: '#d4739a',
      secondary: '#ffdce8',
      accent: '#8c5870',
      background: '#fff7fb',
      surface: 'rgba(255, 255, 255, 0.58)',
      surfaceAlt: 'rgba(255, 255, 255, 0.32)',
      textPrimary: '#38252d',
      textSecondary: '#6b4a58',
      border: 'rgba(140, 88, 112, 0.18)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#6b3d52',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.58, blur: 20, radius: 24, borderWidth: 1 },
    effects: { shadow: 'medium', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.8, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '夜',
    colors: {
      primary: '#8fb8e8',
      secondary: '#2a3550',
      accent: '#a9c8f0',
      background: '#14171f',
      surface: 'rgba(255, 255, 255, 0.07)',
      surfaceAlt: 'rgba(255, 255, 255, 0.04)',
      textPrimary: '#eef1f6',
      textSecondary: '#a8b2c4',
      border: 'rgba(255, 255, 255, 0.14)',
      success: '#6ee7a8',
      warning: '#f0c674',
      danger: '#f28b96',
      focusRing: '#a9c8f0',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.07, blur: 24, radius: 20, borderWidth: 1 },
    effects: { shadow: 'dramatic', glow: true, noise: false },
    motion: { preset: 'float', intensity: 0.7, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '紙',
    colors: {
      primary: '#4a4a48',
      secondary: '#e8e4dc',
      accent: '#6b5b47',
      background: '#faf8f4',
      surface: '#ffffff',
      surfaceAlt: '#f4f1ea',
      textPrimary: '#26241f',
      textSecondary: '#5c584e',
      border: 'rgba(38, 36, 31, 0.14)',
      success: '#2f6d4a',
      warning: '#8a5a12',
      danger: '#a83232',
      focusRing: '#26241f',
    },
    typography: { ...baseTypography, lineHeight: 1.8 },
    surfaces: { style: 'soft', opacity: 1, blur: 0, radius: 8, borderWidth: 0 },
    effects: { shadow: 'soft', glow: false, noise: false },
    motion: { preset: 'none', intensity: 0, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '清晨',
    colors: {
      primary: '#4b8fa8',
      secondary: '#d6ecf2',
      accent: '#2f6b80',
      background: '#f5fbfd',
      surface: 'rgba(255, 255, 255, 0.7)',
      surfaceAlt: 'rgba(255, 255, 255, 0.45)',
      textPrimary: '#1f3038',
      textSecondary: '#4a5c66',
      border: 'rgba(47, 107, 128, 0.18)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#2f6b80',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.7, blur: 16, radius: 28, borderWidth: 1 },
    effects: { shadow: 'soft', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.6, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '森',
    colors: {
      primary: '#2f7d54',
      secondary: '#dcecdf',
      accent: '#1f5c3d',
      background: '#f4faf5',
      surface: 'rgba(255, 255, 255, 0.7)',
      surfaceAlt: 'rgba(255, 255, 255, 0.44)',
      textPrimary: '#1c2b22',
      textSecondary: '#48584e',
      border: 'rgba(31, 92, 61, 0.18)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#1f5c3d',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.7, blur: 18, radius: 22, borderWidth: 1 },
    effects: { shadow: 'soft', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.6, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '暮',
    colors: {
      primary: '#e08a5a',
      secondary: '#3a2c3f',
      accent: '#f0a878',
      background: '#1c1622',
      surface: 'rgba(255, 255, 255, 0.07)',
      surfaceAlt: 'rgba(255, 255, 255, 0.04)',
      textPrimary: '#f4ebe6',
      textSecondary: '#c0aeb8',
      border: 'rgba(255, 255, 255, 0.14)',
      success: '#6ee7a8',
      warning: '#f0c674',
      danger: '#f28b96',
      focusRing: '#f0a878',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.07, blur: 22, radius: 20, borderWidth: 1 },
    effects: { shadow: 'dramatic', glow: true, noise: false },
    motion: { preset: 'float', intensity: 0.7, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '海',
    colors: {
      primary: '#1f7a8c',
      secondary: '#d2ecf0',
      accent: '#125866',
      background: '#f2fafb',
      surface: 'rgba(255, 255, 255, 0.68)',
      surfaceAlt: 'rgba(255, 255, 255, 0.4)',
      textPrimary: '#163034',
      textSecondary: '#42585c',
      border: 'rgba(18, 88, 102, 0.18)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#125866',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.68, blur: 18, radius: 26, borderWidth: 1 },
    effects: { shadow: 'soft', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.6, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '墨',
    colors: {
      primary: '#3a3a3a',
      secondary: '#2a2a2a',
      accent: '#8a8a8a',
      background: '#131313',
      surface: 'rgba(255, 255, 255, 0.06)',
      surfaceAlt: 'rgba(255, 255, 255, 0.03)',
      textPrimary: '#ececec',
      textSecondary: '#a6a6a6',
      border: 'rgba(255, 255, 255, 0.16)',
      success: '#6ee7a8',
      warning: '#f0c674',
      danger: '#f28b96',
      focusRing: '#cfcfcf',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'outline', opacity: 0.06, blur: 0, radius: 6, borderWidth: 1 },
    effects: { shadow: 'soft', glow: false, noise: false },
    motion: { preset: 'none', intensity: 0, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '蜜',
    colors: {
      primary: '#b8791f',
      secondary: '#f5e6c8',
      accent: '#8a5a12',
      background: '#fdf8ef',
      surface: 'rgba(255, 255, 255, 0.62)',
      surfaceAlt: 'rgba(255, 255, 255, 0.36)',
      textPrimary: '#3a2c16',
      textSecondary: '#5f4c30',
      border: 'rgba(138, 90, 18, 0.2)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#8a5a12',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'soft', opacity: 0.62, blur: 12, radius: 18, borderWidth: 1 },
    effects: { shadow: 'soft', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.5, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '薰衣草',
    colors: {
      primary: '#7c5cc4',
      secondary: '#e6ddf5',
      accent: '#5a3d9c',
      background: '#f8f5fd',
      surface: 'rgba(255, 255, 255, 0.66)',
      surfaceAlt: 'rgba(255, 255, 255, 0.4)',
      textPrimary: '#2a2338',
      textSecondary: '#544a68',
      border: 'rgba(90, 61, 156, 0.18)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#5a3d9c',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.66, blur: 20, radius: 24, borderWidth: 1 },
    effects: { shadow: 'medium', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.7, reduceMotionFallback: true },
  },
  {
    schemaVersion: 1,
    name: '珊瑚',
    colors: {
      primary: '#e06a5a',
      secondary: '#fbdcd4',
      accent: '#b8443a',
      background: '#fff6f3',
      surface: 'rgba(255, 255, 255, 0.6)',
      surfaceAlt: 'rgba(255, 255, 255, 0.34)',
      textPrimary: '#3a221e',
      textSecondary: '#66443e',
      border: 'rgba(184, 68, 58, 0.18)',
      success: '#2f7d5c',
      warning: '#8a5a12',
      danger: '#b03050',
      focusRing: '#b8443a',
    },
    typography: { ...baseTypography },
    surfaces: { style: 'glass', opacity: 0.6, blur: 16, radius: 22, borderWidth: 1 },
    effects: { shadow: 'medium', glow: false, noise: false },
    motion: { preset: 'soft', intensity: 0.7, reduceMotionFallback: true },
  },
]

export const DEFAULT_THEME: ThemeDefinition = PRESET_THEMES[0]!

/** 使用者按下「還原預設」時用的。 */
export function defaultThemeDefinition(): ThemeDefinition {
  return structuredClone(DEFAULT_THEME)
}

/**
 * 中性黑白。
 *
 * 用於「必須有字面色值」的少數場合：
 *   - <input type="color"> 的 fallback（該元素不接受非法值）
 *   - 演算法的邊界值（取色失敗時的保底）
 *
 * 集中在這裡而非散落各處，是為了讓 --sr-* token 規則保持有意義 ——
 * 有例外是正常的，例外沒有名字才是問題。
 */
export const NEUTRAL = {
  black: '#000000',
  white: '#ffffff',
  nearBlack: '#1a1a1a',
} as const
